services:
  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    depends_on:
      - influxdb
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdfb-storage:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    env_file:
      - ./influxdb/influxv2.env

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
    restart: unless-stopped
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - ./influxdb/influxv2.env

  publishers:
    build:
      dockerfile: publisher/.dockerfile

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    restart: unless-stopped
    expose:
      - 1883
      - 9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

volumes:
  grafana-storage: {}
  influxdfb-storage: {}
  mosquitto-config: {}
  mosquitto-data: {}
  mosquitto-log: {}
